
<form runat="server">
<h2>Admin</h2>

TODO: add GridView Control 
TODO: add SqlDataSource Control that uses MYSQL 

<asp:SqlDataSource id="dsCollectionQueue" 
		ConnectionString="<%$ConnectionStrings:Database_CollectionItemQueue %>" 
		ProviderName="<%$ ConnectionStrings:Database_CollectionItemQueue.providerName%>"
		SelectCommand = "SELECT `collectionitemqueue`.`ItemID`,
						    `collectionitemqueue`.`ItemTitle`,
						    `collectionitemqueue`.`ItemUrl`,
						    `collectionitemqueue`.`ItemDescription`,
						    `collectionitemqueue`.`ItemTags`,
						    `collectionitemqueue`.`ItemProcessed`
						FROM `ga`.`collectionitemqueue`;
						 "
		UpdateCommand = "UPDATE `collectionitemqueue`
						SET
						`ItemTitle` = @ItemTitle,
						`ItemUrl` = @ItemUrl,
						`ItemDescription` = @ItemDescription,
						`ItemTags` = @ItemTags
						WHERE `ItemID` = @ItemID;
						"
		DeleteCommand = "DELETE FROM `ga`.`collectionitemqueue` WHERE `ItemID` = @ItemID;"


			runat="server">
		</asp:SqlDataSource>
		<%-- 	UpdateCommand = ""
		DeleteCommand = ""
		InsertCommand = ""
 --%>

<asp:GridView id="gvCollectionQueue" 
	DataSourceID="dsCollectionQueue"
	DataKeyNames="ItemID"
	AutoGenerateColumns="true"
	AutoGenerateEditButton="true"
	AutoGenerateDeleteButton="true" 
	runat="server">
	</asp:GridView>


<asp:FormView id="fvCollectionQueue"
	DataSourceID="dsCollectionQueue"
	DataKeyNames="ItemID"
	runat="server"
	AllowPaging="true"
	DefaultMode="Insert"
	>
	<InsertItemTemplate>
		Title: <asp:TextBox id="txtItemTitle" runat="server" Text='<%# Eval("ItemTitle") %>' ></asp:TextBox><br>
		URL:<asp:TextBox id="txtItemUrl" runat="server" Text='<%# Eval("ItemUrl") %>' ></asp:TextBox><br>
		Description:<asp:TextBox id="txtItemDescription" runat="server" Text='<%# Eval("ItemDescription") %>' TextMode="MultiLine" ></asp:TextBox><br>
		Tags: <asp:TextBox id="txtItemTags" runat="server" Text='<%# Eval("ItemTags") %>' ></asp:TextBox><br>
		<asp:LinkButton id="lbInsertItem" runat="server" CommandName="Insert" OnClick="fvCollectionQueue_Insert" ></asp:LinkButton>
	</InsertItemTemplate>
	<ItemTemplate>
		<asp:Label id="lblItemTitle" runat="server" Text='<%# Eval("ItemTitle") %>' />
	</ItemTemplate>
</asp:FormView>

	</form>

