//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Web {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.SqlDataSource dsCollectionQueue;
		
		protected System.Web.UI.WebControls.GridView gvCollectionQueue;
		
		protected System.Web.UI.WebControls.FormView fvCollectionQueue;
		
		protected System.Web.UI.WebControls.TextBox txtItemTitle;
		
		protected System.Web.UI.WebControls.TextBox txtItemUrl;
		
		protected System.Web.UI.WebControls.TextBox txtItemDescription;
		
		protected System.Web.UI.WebControls.TextBox txtItemTags;
		
		protected System.Web.UI.WebControls.LinkButton lbInsertItem;
		
		protected System.Web.UI.WebControls.Label lblItemTitle;
	}
}
