//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Web {
	
	
	public partial class UserView {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblCount;
		
		protected System.Web.UI.WebControls.DataList lvCollectionItems;
		
		protected System.Web.UI.WebControls.LinkButton lbViewItem;
		
		protected System.Web.UI.WebControls.FormView fvCollectionItem;
		
		protected System.Web.UI.WebControls.Label lblItemTitle;
		
		protected System.Web.UI.WebControls.Label lblItemUrl;
		
		protected System.Web.UI.WebControls.Label lblItemDescription;
	}
}
